import type { NorthDestinationData } from "@/components/NorthDestinationTemplate";

const describe = (locations: string[], prefix: string) =>
  Object.fromEntries(locations.map((location) => [location, `${prefix} Add this stop for a better-paced route with local context, food, sights and transport planning.`]));

const delhiLocations = [
  "India Gate",
  "Red Fort",
  "Qutub Minar",
  "Lotus Temple",
  "Humayun's Tomb",
  "Jama Masjid",
  "Connaught Place",
  "Chandni Chowk & Old Delhi food walk",
  "Akshardham Temple",
  "Lodhi Garden",
  "Hauz Khas Village",
  "Dilli Haat",
  "National Museum",
  "Gurudwara Bangla Sahib",
];

const himachalLocations = [
  "Shimla (Mall Road & Ridge)",
  "Manali (Solang / Old Manali)",
  "Dharamshala (McLeod Ganj & Tibetan culture)",
  "Kullu Valley",
  "Kasol & Parvati Valley",
  "Spiti Valley (Kaza, Kibber)",
  "Lahaul & Keylong",
  "Kinnaur (Kalpa, Sangla, Chitkul)",
  "Kasauli",
  "Chamba",
  "Dalhousie",
  "Palampur",
  "Tattapani (hot springs)",
  "Solan",
  "Narkanda",
  "Rampur",
  "Barot",
  "Shoja / Jalori Pass",
  "Khajjiar",
  "Kangra (Fort & valleys)",
  "Rohtang Pass / Atal Tunnel access",
  "Great Himalayan National Park",
  "Chitkul",
];

const uttarakhandLocations = [
  "Rishikesh (Yoga & River Rafting)",
  "Haridwar (Ganga Aarti & Ghats)",
  "Nainital (Lake & Hill Views)",
  "Mussoorie (Hill Station)",
  "Jim Corbett National Park",
  "Kedarnath",
  "Badrinath",
  "Auli",
  "Valley of Flowers",
  "Joshimath",
  "Ranikhet",
  "Almora",
  "Mukteshwar",
  "Chopta",
  "Lansdowne",
  "Tehri Lake",
  "Kausani",
  "Binsar",
  "Dehradun",
  "Pithoragarh",
  "Munsiyari",
];

const jammuKashmirLocations = [
  "Srinagar (Dal Lake & Mughal Gardens)",
  "Gulmarg (Apharwat Peak & Gondola)",
  "Pahalgam (Aru Valley & Betaab Valley)",
  "Sonamarg (Thajiwas Glacier & river walks)",
  "Jammu City",
  "Katra (base for Vaishno Devi)",
  "Patnitop",
  "Bhaderwah",
  "Doda",
  "Kishtwar",
  "Anantnag",
  "Pulwama",
  "Shopian",
  "Bandipora",
  "Baramulla",
  "Kupwara",
  "Rajouri",
  "Poonch",
  "Udhampur",
  "Kathua",
  "Yusmarg",
  "Doodhpathri",
  "Wular Lake",
  "Shankaracharya Temple",
  "Hazratbal Shrine",
  "Nishat Bagh",
  "Shalimar Bagh",
  "Aru Valley",
  "Lidder Valley",
  "Betaab Valley",
];

const uttarPradeshLocations = [
  "Varanasi (Kashi)",
  "Sarnath",
  "Agra (Taj Mahal & Fort)",
  "Fatehpur Sikri",
  "Mathura & Vrindavan",
  "Lucknow",
  "Prayagraj",
  "Ayodhya",
  "Jhansi",
  "Chitrakoot",
  "Dudhwa National Park",
  "Kushinagar",
  "Meerut",
  "Noida",
  "Gorakhpur",
];

const punjabLocations = [
  "Amritsar (Golden Temple)",
  "Wagah Border",
  "Jallianwala Bagh",
  "Anandpur Sahib",
  "Patiala",
  "Ludhiana",
  "Bathinda",
  "Hoshiarpur",
  "Kapurthala",
  "Rupnagar (Ropar)",
  "Phagwara",
  "Kiratpur Sahib",
  "Talwandi Sabo (Damdama Sahib)",
];

const haryanaLocations = [
  "Kurukshetra",
  "Panipat",
  "Sultanpur Bird Sanctuary",
  "Gurugram",
  "Faridabad",
  "Panchkula",
  "Karnal",
  "Hisar",
  "Jind",
  "Kurukshetra Jyotisar",
  "Pinjore Gardens",
];

const chandigarhLocations = [
  "Rock Garden",
  "Sukhna Lake",
  "Rose Garden",
  "Capitol Complex",
  "Sector 17 Market",
  "Elante Mall",
  "Leisure Valley",
  "Garden of Silence",
  "Government Museum & Art Gallery",
  "Cactus Garden",
  "Japanese Garden",
  "Pinjore Gardens",
  "Shimla gateway",
  "Kasauli gateway",
  "Manali gateway",
];

const routeSteps = (first: string, second: string, third: string) => [
  { title: first, meta: "Step 1", text: "Start with the easiest arrival point, first check-in and nearby experiences." },
  { title: second, meta: "Step 2", text: "Add the core sights in the right order, with transport and rest time planned." },
  { title: third, meta: "Step 3", text: "Finish with a smooth exit, optional extensions and clear next-day logistics." },
];

export const northDestinationData: Record<string, NorthDestinationData> = {
  delhi: {
    name: "Delhi",
    image: "/images/north-india/delhi.jpg",
    bestSeason: "Oct - Mar",
    highlights: "Historic monuments, old-city food walks, museums, markets and smooth arrival logistics.",
    badge: "City break route",
    moodTitle: "Culture, food and monuments.",
    moodText: "Delhi works best when old-city lanes, major monuments and modern dining are paced by zone instead of rushed across traffic.",
    locations: delhiLocations,
    descriptions: {
      ...describe(delhiLocations, "Delhi blends monuments, markets and food walks."),
      "India Gate": "National memorial lawns, evening walks and central Delhi photo stops.",
      "Chandni Chowk & Old Delhi food walk": "Old Delhi lanes, snacks, spices and heritage streets planned with a local flow.",
    },
    routeSteps: routeSteps("Arrive central", "Explore by zone", "Close with food"),
    safety: ["Plan monuments early to avoid heat and crowds.", "Use app cabs or trusted transport between zones.", "Wear comfortable shoes for markets and old city walks."],
    avoid: ["Do not overpack too many monuments in one day.", "Avoid unverified guides and random transport quotes.", "Keep valuables secure in crowded markets."],
    extraChips: ["Food walks", "Museums", "Markets"],
  },
  "himachal-pradesh": {
    name: "Himachal Pradesh",
    image: "/images/north-india/himachal.jpg",
    bestSeason: "Mar - Jun, Sep - Nov",
    highlights: "Hill towns, apple valleys, Tibetan culture, high passes and scenic mountain stays.",
    badge: "Mountain stay route",
    moodTitle: "Slow hills, not rushed drives.",
    moodText: "Himachal needs careful drive timing, hill-stay selection and route order, especially when combining valleys.",
    locations: himachalLocations,
    descriptions: describe(himachalLocations, "Himachal routes are strongest when drives and stays are paced by valley."),
    routeSteps: routeSteps("Choose the valley", "Add viewpoints", "Keep buffer drives"),
    safety: ["Check hill road status before long drives.", "Carry layers even in warmer months.", "Use local guidance for treks and remote valleys."],
    avoid: ["Avoid night driving on unfamiliar mountain roads.", "Do not combine too many valleys in a short trip.", "Avoid peak-season stay bookings at the last minute."],
    extraChips: ["Shimla", "Manali", "Spiti", "Dharamshala"],
  },
  uttarakhand: {
    name: "Uttarakhand",
    image: "/images/north-india/uttarakhand.jpg",
    bestSeason: "Mar - Jun, Sep - Nov",
    highlights: "River towns, sacred ghats, forest safaris, lake hills and Himalayan gateways.",
    badge: "River and hills route",
    moodTitle: "Spiritual, forest and hill balance.",
    moodText: "Uttarakhand works best when river towns, hill stations and forest stays are not forced into one rushed loop.",
    locations: uttarakhandLocations,
    descriptions: describe(uttarakhandLocations, "Uttarakhand offers sacred towns, hill views, treks and forest experiences."),
    routeSteps: routeSteps("Start by river", "Move to hills", "Add forest or trek"),
    safety: ["Book Corbett safaris and permits early.", "Respect temple rules and local customs.", "Use guides for treks and high-altitude routes."],
    avoid: ["Avoid mountain driving after dark.", "Do not trek late in the day.", "Avoid disposable plastic in forest and hill zones."],
    extraChips: ["Rishikesh", "Nainital", "Corbett", "Auli"],
  },
  "jammu-and-kashmir": {
    name: "Jammu & Kashmir",
    image: "/images/north-india/jammu.jpg",
    bestSeason: "May - Sep, Dec - Feb for snow",
    highlights: "Alpine lakes, valleys, Mughal gardens, winter sports and pilgrimage gateways.",
    badge: "Premium leisure route",
    moodTitle: "Valleys, lakes and measured transfers.",
    moodText: "Kashmir needs clean transfer planning, flexible weather handling and enough time around Srinagar, Gulmarg and Pahalgam.",
    locations: jammuKashmirLocations,
    descriptions: describe(jammuKashmirLocations, "Kashmir combines lake stays, valley drives, gardens, shrines and mountain views."),
    routeSteps: routeSteps("Settle in Srinagar", "Add valley drives", "Finish with leisure"),
    safety: ["Check road and weather updates before valley drives.", "Carry layers for sudden weather shifts.", "Use trusted local transport and guides."],
    avoid: ["Avoid restricted zones without permits.", "Do not pack high-altitude excursions without guidance.", "Avoid littering in meadows and lake areas."],
    extraChips: ["Srinagar", "Gulmarg", "Pahalgam", "Sonamarg"],
  },
  "uttar-pradesh": {
    name: "Uttar Pradesh",
    image: "/images/north-india/uttar-pradesh.jpg",
    bestSeason: "Oct - Mar",
    highlights: "Heritage cities, sacred ghats, Mughal architecture, Buddhist sites and riverfront rituals.",
    badge: "Heritage route",
    moodTitle: "Sacred cities and heritage circuits.",
    moodText: "Uttar Pradesh is best planned as focused circuits: Agra-Mathura, Lucknow-Ayodhya, or Kashi-Sarnath.",
    locations: uttarPradeshLocations,
    descriptions: describe(uttarPradeshLocations, "Uttar Pradesh brings together temples, ghats, monuments, cuisine and deep heritage."),
    routeSteps: routeSteps("Pick the circuit", "Add guided sights", "Keep ritual timing"),
    safety: ["Book major monuments and guides in advance.", "Respect temple and ghat customs.", "Plan long intercity drives with daylight buffers."],
    avoid: ["Avoid touts near crowded tourist sites.", "Do not rush Varanasi or Agra into half-day visits.", "Avoid leather items where temple rules restrict them."],
    extraChips: ["Agra", "Varanasi", "Lucknow", "Ayodhya"],
  },
  punjab: {
    name: "Punjab",
    image: "/images/north-india/punjab.jpg",
    bestSeason: "Oct - Mar",
    highlights: "Sikh heritage, warm hospitality, border ceremony, farms, food and living culture.",
    badge: "Culture route",
    moodTitle: "Heritage, food and hospitality.",
    moodText: "Punjab trips feel strongest when Amritsar, border timing, food stops and countryside stays are planned together.",
    locations: punjabLocations,
    descriptions: describe(punjabLocations, "Punjab is rich with gurdwaras, food, crafts, history and generous local hospitality."),
    routeSteps: routeSteps("Start in Amritsar", "Add heritage towns", "Finish with food and farms"),
    safety: ["Cover your head and dress modestly at gurdwaras.", "Use planned transport for border ceremony days.", "Keep time for langar and local food stops."],
    avoid: ["Do not photograph where signs prohibit it.", "Avoid unverified guides in busy heritage areas.", "Do not leave belongings unattended in crowded markets."],
    extraChips: ["Golden Temple", "Wagah", "Patiala", "Food"],
  },
  haryana: {
    name: "Haryana",
    image: "/images/north-india/haryana.jpg",
    bestSeason: "Oct - Mar",
    highlights: "Short heritage breaks, Kurukshetra, birding, rural culture and easy ex-Delhi routes.",
    badge: "Short trip route",
    moodTitle: "Compact breaks from Delhi.",
    moodText: "Haryana is ideal for short, focused circuits with heritage, birding, gardens and easy city access.",
    locations: haryanaLocations,
    descriptions: describe(haryanaLocations, "Haryana works well for heritage stops, birding, gardens and countryside breaks."),
    routeSteps: routeSteps("Start ex-Delhi", "Add heritage stop", "Return easy"),
    safety: ["Carry sun protection for day trips.", "Keep distance and quiet in birding zones.", "Use local guidance for rural or heritage detours."],
    avoid: ["Avoid late-night rural driving without guidance.", "Do not disturb wildlife at sanctuaries.", "Avoid trespassing in restoration or restricted areas."],
    extraChips: ["Kurukshetra", "Panipat", "Sultanpur", "Pinjore"],
  },
  chandigarh: {
    name: "Chandigarh",
    image: "/images/north-india/chandigarh.jpg",
    bestSeason: "Oct - Mar",
    highlights: "Clean modernist city, lake walks, gardens, museums and a smooth gateway to Himachal.",
    badge: "Gateway route",
    moodTitle: "Clean city, easy gateway.",
    moodText: "Chandigarh is best used as a calm city stay or launchpad into Kasauli, Shimla, Manali and the hills.",
    locations: chandigarhLocations,
    descriptions: describe(chandigarhLocations, "Chandigarh offers clean urban planning, gardens, lake walks and hill gateway logistics."),
    routeSteps: routeSteps("Settle in the city", "See lake and gardens", "Move toward hills"),
    safety: ["Use official parking and planned city transfers.", "Respect quiet zones around government and museum areas.", "Wear comfortable shoes for Rock Garden and lake walks."],
    avoid: ["Avoid restricted government areas without access.", "Do not litter around lake and garden zones.", "Avoid loud late-night behavior in residential sectors."],
    extraChips: ["Rock Garden", "Sukhna Lake", "Kasauli", "Shimla"],
  },
};
